### ISSUE TITLE
Maybe timeout should be a config property instead of being exposed by the API

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/playground-service#15]
The [Executor Service](https://github.com/coding-eval-platform/executor-service) requires an execution timeout. Up to now we are receiving that timeout in this wrapper, and bypassing it to the Executor Service.

Should we do it like this? Or configure an overall timeout on application boot, and stick to it till another value is set and deployed?

**Comment by juanmbellini** [comment]
@lobo What do you think about this? The difference would be sending or not sending the timeout value in each execution request. If is sent, each request can have its own timeout. If it is configured, is always the same value for all executions.

**Comment by lobo** [comment]
I'd prefer it to be sent @juanmbellini and then, for now, always send the same value. So it can be configured differently in the future if needed. If it's the same effort on your end, please go ahead with this approach.

**Comment by juanmbellini** [comment]
No, doing that is more complex. We can:
- Configure once when compiling the code
- Be part of the exposed API and the consumer (the frontend) sets the timeout of each execution.
