### ISSUE TITLE
Add an authoring system?

### ISSUE THREAD

**Issue by juanmbellini** [coding-eval-platform/playground-service#23]
Should we add some sort of authoring for this? Are executions public? Or each user (including students, which do not have any role defined in the platform at the moment) should have privacy?

**Comment by lobo** [comment]
For the first version of this project, we'll leave that to chance. That is, executions will be public even if that implies a security vulnerability. @juanmbellini

**Comment by juanmbellini** [comment]
It’s not a security vulnerability, just a privacy issue. However, we could not store who performed each execution.
@lobo

**Comment by lobo** [comment]
OK, let's forget about this privacy issue for the first iteration :)

**Comment by juanmbellini** [comment]
Even though we will add the authentication filter #22 , we won't impose any restriction in the use of this microservice. Whatsmore, we won't store who performed an execution.
